// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrV3ezWFcr7FlN-7cD4pYq1FYdUd_eozo',
    appId: '1:430779539965:web:47a3ecd0f71e3d8f30f994',
    messagingSenderId: '430779539965',
    projectId: 'polyspace-project',
    authDomain: 'polyspace-project.firebaseapp.com',
    storageBucket: 'polyspace-project.firebasestorage.app',
    measurementId: 'G-1KZDWFGQPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxSBTwKIkse1ZGUjDuhp0_e1XumJvGVsY',
    appId: '1:430779539965:android:44c0b4f4bac84d0630f994',
    messagingSenderId: '430779539965',
    projectId: 'polyspace-project',
    storageBucket: 'polyspace-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACBID8Tv2Bm4kL1zgCbp5DB2eqW5fUn7E',
    appId: '1:430779539965:ios:6c628eb656aee2de30f994',
    messagingSenderId: '430779539965',
    projectId: 'polyspace-project',
    storageBucket: 'polyspace-project.firebasestorage.app',
    iosBundleId: 'com.example.polyspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrV3ezWFcr7FlN-7cD4pYq1FYdUd_eozo',
    appId: '1:430779539965:web:d5b6e718adf77bf930f994',
    messagingSenderId: '430779539965',
    projectId: 'polyspace-project',
    authDomain: 'polyspace-project.firebaseapp.com',
    storageBucket: 'polyspace-project.firebasestorage.app',
    measurementId: 'G-TP1235Q6XV',
  );
}
